language: node_js
node_js:
  - lts/*
env:
  global:
    - SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=9cdJAJEmw2GLKBfbnciQTu90nm1LiSHnt
install:
  - npm install
script:
  - npm run build:ts
  - npm run build
  - npm run test
  - npm run coveralls
